### ISSUE TITLE
Add curlpod

### ISSUE THREAD

**Issue by sgoings** [helm/charts-classic#27]
In the Kubernetes documentation they use the following pod definition for being able to manual test services within the cluster with curl/nslookup/etc:

```
apiVersion: v1
kind: Pod
metadata:
  name: curlpod
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: curlcontainer
  restartPolicy: Always
```

Then you execute:

```
kubectl exec curlpod -- nslookup nginxsvc
```

It would be nifty to have this available as a helm chart (would have helped @bacongobbler with testing #25)
